apiVersion: v1
kind: Secret
metadata:
  name: github-actions-runner
  namespace: dev
  annotations:
data:
  token: Z2hwX1l5cGwxNzF3TVJENVRMUVU4UFhxODQ1YkpnbHVPZTNvRThDQQo=
  user: bXVsdGlwbHktc2VydmljZQo=