---
apiVersion: v1
kind: Service
metadata:
  name: $service
  labels:
    project: momentum-money
    bu: momentum-money
    app: $service
    target-deployment: $deployment
spec:
  selector:
    app.kubernetes.io/instance: $deployment
  ports:
  - name: http
    port: 8080
    protocol: TCP
  - name: https
    port: 8443
    protocol: TCP
  - name: management
    port: 9990
    protocol: TCP
